name: Bug report
description: Report a bug. For security vulnerabilities see Report a security vulnerability in the templates.
title: "BUG: <Please write a comprehensive title after the 'BUG: ' prefix>"
labels: [00 - Bug]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. Before creating a new
        issue, please make sure to take a few minutes to check the issue tracker
        for existing issues about the bug.
        Please refer to [minimal reproducible example](https://stackoverflow.com/help/mcve).

  - type: textarea
    attributes:
      label: "Describe the issue:"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Reproduce the code example:"
      description: >
        A short code or CLI example that reproduces the problem/missing feature. It
        should be self-contained, i.e., can be copy-pasted into the Python
        interpreter.
      placeholder: |
        << your code or command line here >>
      render: python
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Error message:"
      description: >
        Please include full error message, if any.
      placeholder: |
        << Full traceback starting from `Traceback: ...` >>
      render: shell

  - type: textarea
    attributes:
      label: "Runtime information:"
      description: >
        Include any runtime information here
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Context for the issue:"
      description: |
        Please supply your context for the issue.
      placeholder: |
        << your explanation here >>
    validations:
      required: false
