# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: test

on:
  push:
    branches: [default-branch1]
  pull_request:
    branches: [default-branch2]

jobs:
  test:
    # Step 1. Set up operating system
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9"]
        exclude:
          - os: windows-latest
            python-version: "3.8"
    steps:
      # Step 3. Check-out repository so we can access its contents
      - uses: actions/checkout@v3
      # Step 2. Set up Python 3.9
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      # step 3. Install the dependencies from requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 pytest pytest-cov
          pip install -r requirements/test.txt
      # Step 5. Install our pycounts package
      - name: Install package
        run: |
          pip install -e .
      # Step 5. Lint the files with flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true
      # Step 6. Run the tests
      - name: Test with pytest
        run: |
          pytest tests/ --cov=package_name --cov-report=xml
      # Step 7. Use Codecov to track coverage
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml # coverage report
          fail_build_if_error: true # terminate workflow if there's an error
